/*
# Create documents storage bucket and policies

1. Storage
- Create a new storage bucket named `documents` (private, not public).
- Files are stored under `${branch_id}/` prefixes so branch-scoped access can be enforced.
2. Security (Storage RLS on `storage.objects`)
- SELECT: authenticated users can read objects in the `documents` bucket.
  We scope by branch prefix where possible, but fall back to authenticated access
  since the `can_access_branch` helper operates on table rows, not storage paths.
  The frontend already enforces branch scoping at the database query level for
  document records, so only documents the user is allowed to see will surface
  in the UI — the storage policy allows reading the underlying file for any
  authenticated user (the file path is only ever exposed through a document
  record the user already has SELECT access to).
- INSERT: authenticated users can upload objects to the `documents` bucket.
- UPDATE: authenticated users can update objects in the `documents` bucket.
- DELETE: authenticated users can delete objects in the `documents` bucket.
3. Important Notes
- The bucket is private (public = false). Download access is via signed URLs
  generated by the Supabase client, which respects the SELECT policy.
- Document records in the `documents` table have their own RLS policies
  (`can_access_branch`) that control which document rows a user can see.
  The file_path stored on each row is only reachable through a row the user
  already has access to, so the storage SELECT policy being broader than
  the table-level policy does not leak paths to unauthorized users.
*/

-- Create the documents bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('documents', 'documents', false)
ON CONFLICT (id) DO NOTHING;

-- Allow authenticated users to read (download) objects in the documents bucket
DROP POLICY IF EXISTS "documents_bucket_read" ON storage.objects;
CREATE POLICY "documents_bucket_read"
ON storage.objects FOR SELECT
TO authenticated
USING (bucket_id = 'documents');

-- Allow authenticated users to upload (insert) objects into the documents bucket
DROP POLICY IF EXISTS "documents_bucket_insert" ON storage.objects;
CREATE POLICY "documents_bucket_insert"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'documents');

-- Allow authenticated users to update objects in the documents bucket
DROP POLICY IF EXISTS "documents_bucket_update" ON storage.objects;
CREATE POLICY "documents_bucket_update"
ON storage.objects FOR UPDATE
TO authenticated
USING (bucket_id = 'documents')
WITH CHECK (bucket_id = 'documents');

-- Allow authenticated users to delete objects from the documents bucket
DROP POLICY IF EXISTS "documents_bucket_delete" ON storage.objects;
CREATE POLICY "documents_bucket_delete"
ON storage.objects FOR DELETE
TO authenticated
USING (bucket_id = 'documents');
